/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lfcinvention_RemoteVision_VideoService */

#ifndef _Included_com_lfcinvention_RemoteVision_VideoService
#define _Included_com_lfcinvention_RemoteVision_VideoService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lfcinvention_RemoteVision_VideoService
 * Method:    nativeCreateServerInstance
 * Signature: (Lcom/lfcinvention/RemoteVision/NativeError;ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_lfcinvention_RemoteVision_VideoService_nativeCreateServerInstance
  (JNIEnv *, jobject, jobject, jint, jstring, jint);

/*
 * Class:     com_lfcinvention_RemoteVision_VideoService
 * Method:    nativeGetPreviewImage
 * Signature: (ILcom/lfcinvention/RemoteVision/NativePreviewImage;)Lcom/lfcinvention/RemoteVision/NativeError;
 */
JNIEXPORT jobject JNICALL Java_com_lfcinvention_RemoteVision_VideoService_nativeGetPreviewImage
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_lfcinvention_RemoteVision_VideoService
 * Method:    nativeDestroyServerInstance
 * Signature: (I)Lcom/lfcinvention/RemoteVision/NativeError;
 */
JNIEXPORT jobject JNICALL Java_com_lfcinvention_RemoteVision_VideoService_nativeDestroyServerInstance
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_lfcinvention_RemoteVision_VideoService
 * Method:    nativeStartService
 * Signature: (I)Lcom/lfcinvention/RemoteVision/NativeError;
 */
JNIEXPORT jobject JNICALL Java_com_lfcinvention_RemoteVision_VideoService_nativeStartService
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_lfcinvention_RemoteVision_VideoService
 * Method:    nativeStopService
 * Signature: (I)Lcom/lfcinvention/RemoteVision/NativeError;
 */
JNIEXPORT jobject JNICALL Java_com_lfcinvention_RemoteVision_VideoService_nativeStopService
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_lfcinvention_RemoteVision_VideoService
 * Method:    nativeGetBoundAddress
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lfcinvention_RemoteVision_VideoService_nativeGetBoundAddress
  (JNIEnv *, jobject, jint);


jint JNI_OnLoad(JavaVM *, void *);
#ifdef __cplusplus
}
#endif
#endif
